# Generated by Django 4.2.5 on 2023-09-21 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=43)),
                ('Texto', models.CharField(max_length=400)),
                ('FechaCreacion', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('Creador', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('RespuestaDe', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='foro.post')),
            ],
        ),
    ]
