# Generated by Django 4.2.5 on 2023-09-21 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import login.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='Nickname*')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Dirección e-mail*')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre*')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellidos*')),
                ('user_role', models.CharField(choices=[('USR', 'Usuario'), ('AMG', 'Amigo'), ('SEC', 'Secretaria'), ('TES', 'Tesoreria'), ('PNL', 'Personal'), ('PRS', 'Presidencia'), ('ADM', 'Administrador')], default='USR', max_length=3, verbose_name='Rol De Usuario')),
                ('incomplete', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', login.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Hospitales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
                ('Localidad', models.CharField(max_length=100)),
                ('Provincia', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Socios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodigoSocio', models.CharField(max_length=10)),
                ('Nombre', models.CharField(max_length=15)),
                ('Apellidos', models.CharField(max_length=50)),
                ('FechaNacimiento', models.DateField()),
                ('IBAN', models.CharField(max_length=34)),
                ('TitularIBAN', models.CharField(max_length=15)),
                ('SEPA', models.FileField(upload_to='sepa/%Y/%m/%d')),
                ('PagoRegistrado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Telefono', models.IntegerField()),
                ('Direccion', models.CharField(max_length=200)),
                ('CodigoPostal', models.IntegerField()),
                ('Localidad', models.CharField(max_length=100)),
                ('Provincia', models.CharField(max_length=100)),
                ('Relacion', models.CharField(choices=[('PAT', 'Paternal'), ('HRM', 'Hermandad'), ('FML', 'Familiar'), ('OTR', 'Otro')], default='PAT', max_length=3, null=True)),
                ('Notificar', models.BooleanField(default=True)),
                ('PermisoImagen', models.BooleanField(default=False)),
                ('AceptaUsoDatos', models.BooleanField(default=False)),
                ('Asociado', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='login.socios')),
                ('UserVinculado', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HospitalizaA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tvi', models.DateField(default=django.utils.timezone.now)),
                ('Tvf', models.DateField(default=None, null=True)),
                ('Hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='login.hospitales')),
                ('Socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.socios')),
            ],
        ),
        migrations.CreateModel(
            name='AmigoBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IBAN', models.CharField(max_length=34)),
                ('TitularIBAN', models.CharField(max_length=15)),
                ('SEPA', models.FileField(upload_to='sepa/%Y/%m/%d')),
                ('Tarifa', models.FloatField(null=True)),
                ('PagoRegistrado', models.BooleanField(default=False)),
                ('UserVinculado', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Login', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('Logout', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('User', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='hospitalizaa',
            constraint=models.UniqueConstraint(fields=('Hospital', 'Socio', 'Tvi'), name='Complex Primary Key simulation for HospitalizaA.'),
        ),
        migrations.AddConstraint(
            model_name='accesslog',
            constraint=models.UniqueConstraint(fields=('User', 'Login', 'Logout'), name='Complex Primary Key simulation for AccessLog.'),
        ),
    ]
