# Generated by Django 4.2.5 on 2023-09-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Macros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TarifaSocios', models.FloatField(default=36)),
                ('MinimoAmigos', models.FloatField(default=20)),
                ('diaCobro', models.IntegerField(default=15)),
                ('mesCobro', models.IntegerField(default=4)),
            ],
        ),
    ]
