# Generated by Django 4.2.5 on 2023-09-21 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Destino', models.CharField(choices=[('TODOS', 'Todos'), ('PRSNL', 'Personal')], default='TODOS', max_length=5, null=True)),
                ('Titulo', models.CharField(max_length=30)),
                ('Texto', models.CharField(max_length=400)),
                ('Adjunto', models.FileField(upload_to='attached/%Y/%m/%d')),
                ('FechaCreacion', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('Creador', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vistos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Notice', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='notificaciones.notice')),
                ('User', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='vistos',
            constraint=models.UniqueConstraint(fields=('Notice', 'User'), name='Complex Primary Key simulation for Vistos.'),
        ),
    ]
